# Site settings
baseurl = "https://remorsecs.github.io/"
languageCode = "zh-tw"
title = "Maniac"
theme = "cactus-plus"
googleAnalytics = "UA-113302216-1"
# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
hasCJKLanguage = true
#publishDir = "temp"

[params]
	author = "Maniac"
	description = ""
	bio = ""

	twitter = ""
	facebook = ""

	enableRSS = false
	enableToc = true

	enableDisqus = true
	disqusShortname = ""


	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = false


	enableGoogleAnalytics = true

	enableTwitterCard = true
	# The url for twitter card image, default is avatar.png in static/images directory
	twitterCardImage = ""

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = ""

	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# show latest posts in single page
	showLatestPosts = false
	readMore = ""

	# Share
	enableShare = true
	tweet = ""
	share = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = ""


# Add additional social link entries underneath
[social]
	facebook-square = "https://www.facebook.com/erwin.schrodinger.7"
	twitter-square = "https://www.twitter.com/maniac_tw"
	github-square = "https://www.github.com/remorsecs"
